name: Daily Check-in

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时执行一次
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps firefox

      - name: Execute script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python main.py

      - name: Send Bark Notification Success
        env:
          BARK_KEY: ${{ secrets.BARK_KEY }}
        if: ${{ success() && ${{ secrets.BARK_KEY }} != '' }}
        run: |
          curl -s "https://bark.withlevi.top/${{ secrets.BARK_KEY }}/LINUX DO 每日签到成功完成/✅ 签到任务已完成?icon=https://raw.githubusercontent.com/Orz-3/mini/master/Color/Global.png"

      - name: Send Bark Notification Failure  
        env:
          BARK_KEY: ${{ secrets.BARK_KEY }}
        if: ${{ failure() && ${{ secrets.BARK_KEY }} != '' }}
        run: |
          curl -s "https://bark.withlevi.top/${{ secrets.BARK_KEY }}/LINUX DO 每日签到失败/❌ 签到任务失败?icon=https://raw.githubusercontent.com/Orz-3/mini/master/Color/Global.png" 

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 6
